"""Write docs/case-catalogue.md from the code: every event type and the rule that handles it,
every kind of thing a note can say and what the engine does about it, and the deterministic
keyword floor. Run after adding a rule, an event type or a catalogue kind so the document a
reviewer reads is the one the engine runs.

    python3 scripts/case_catalogue.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hc_valuation.config import load_config  # noqa: E402
from hc_valuation.engine.inputs import EventType  # noqa: E402
from hc_valuation.engine.run import build_registry  # noqa: E402
from hc_valuation.ingest.normalize import _SYNONYMS  # noqa: E402
from hc_valuation.notes.catalogue import ASPECTS  # noqa: E402

OUT = ROOT / "docs" / "case-catalogue.md"


def main() -> int:
    cfg = load_config(ROOT / "rules" / "2026Q3.yaml")
    reg = build_registry(cfg)
    md = cfg.quarter.measurement_date
    lines = [
        "# Case catalogue",
        "",
        "Generated by `scripts/case_catalogue.py` from the code. Three layers decide what happens to an activity row:",
        "",
        "1. **The event type** (the `Event` cell) picks a marking rule. Every spelling in the synonym table maps to one of",
        "   the types below; anything else is unrecognised, blocks the position (M-999), and gets a drafted treatment for a",
        "   person to accept, reject or promote (E-09).",
        "2. **The free text** (`Detail`, `Notes`) is read twice. A deterministic keyword screen (X-105) raises the terms in",
        "   the policy's `note_screen.terms` unless the row's rule handled them. The note reader (Claude) classifies the",
        "   text against the kinds below and raises what no rule took account of (X-130), what conflicts with a column",
        "   (X-131), what supersedes the Portfolio tab (X-126), and any row it could not read (X-132). It quotes; it",
        "   never sets a number. A kind outside the list is `other`, and `other` always reaches a person.",
        "3. **Readiness** gates publication: a review finding leaves the position Needs Review; two review findings from",
        "   different families, or any blocking one, leave it Blocked.",
        "",
        "## Event types and their rules",
        "",
        "| Event | Rule | What it does | Also written as |",
        "|---|---|---|---|",
    ]
    for et in EventType:
        meta, _ = reg.handler_for(et.value, md)
        syn = ", ".join(s for s in _SYNONYMS.get(et.value, ()) if s != et.value.lower())
        lines.append(f"| {et.value} | {meta.rule_id} | {meta.description} | {syn} |")
    lines += [
        "",
        "Anything not in the table: **M-999**, Blocked, with an E-09 draft beside it.",
        "",
        "## What a note can say",
        "",
        "| Kind | Meaning | Handled by | Keyword floor |",
        "|---|---|---|---|",
    ]
    for a in ASPECTS:
        lines.append(f"| `{a.kind.value}` — {a.label} | {a.definition} | {a.handled_by or 'always a person'} | {', '.join(a.terms) or '—'} |")
    lines += [
        "",
        "## The deterministic floor",
        "",
        "With the reader off (no `ANTHROPIC_API_KEY`, or `--note-reader off`) the keyword screen is the only reading of the",
        "text. Its terms, from `rules/2026Q3.yaml`:",
        "",
        "```",
        ", ".join(cfg.note_screen.terms),
        "```",
        "",
        "Per event type, the terms its own rule handles (not re-raised):",
        "",
    ]
    for et, terms in (cfg.note_screen.exempt or {}).items():
        lines.append(f"- {et}: {', '.join(terms)}")
    lines += [
        "",
        "## What the reader may never do",
        "",
        "- Produce, change or suggest a number to book. Its output is text about text.",
        "- Lower a severity, remove a finding, or mark a position Ready.",
        "- Be trusted on a quote: every quote is matched back to the row's own text; an unmatched quote is shown as such.",
        "- Run inside the engine: readings are inputs to `run_valuation`, like market data, so the run is deterministic",
        "  and reproducible from the cache under `data/note_reads/`.",
        "- Run in the test suite: `HC_NOTE_READER=off` is pinned and no key is visible; tests inject fakes.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(list(EventType))} event types, {len(ASPECTS)} kinds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
