"""Build and drive the synthetic test chain: Q3 2026 (real book, decided) → Q4 2026 → Q1 2027 → Q2 2027.

    python3 scripts/synthetic_chain.py q3            # decide + publish the real Q3 book into the chain ledger, emit Q4's input
    python3 scripts/synthetic_chain.py workbook 2026Q4   # write the Q4 workbook (activity rows + metric edits) and malformed variants
    python3 scripts/synthetic_chain.py expect  2026Q4    # write expectations from the workbook + policy, WITHOUT running the engine
    python3 scripts/synthetic_chain.py run     2026Q4    # run the engine and compare with the expectations
    python3 scripts/synthetic_chain.py decide  2026Q4    # record the scripted reviewer decisions, publish, emit the next input
    ... then `workbook 2027Q1`, `expect 2027Q1`, `run 2027Q1`, `decide 2027Q1`, `workbook 2027Q2`, ...

Everything lands under data/quarters/synthetic/: one folder per quarter with the workbook and its
open_items_carry.yaml sidecar, `ledger/` (overrides, published snapshots — never data/), `build/`
(what `hc-valuation build` emitted for each quarter, the next quarter's input among it),
`malformed/` (deliberately broken variants, never part of the chain) and `expectations/`.

**Every opening balance in the chain is produced by the engine plus a recorded decision**: a quarter's
Portfolio tab is the previous quarter's `build` output — booked marks after the scripted decisions
below, published under a second name — and only the activity rows and a handful of operating metrics
are written by hand. The decisions are listed in DECISIONS (named, non-default) and otherwise follow the
policy recommendation; `decisions_<quarter>.md` beside the ledger records every one with its reason.

Every workbook carries a `SYNTHETIC TEST DATA` sheet as its first tab and the word SYNTHETIC in its
file name. Nothing in it is a real position.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import openpyxl
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hc_valuation.api.app import append_override            # noqa: E402
from hc_valuation.api.publish import publish_run           # noqa: E402
from hc_valuation.config import load_config, write_next_policy  # noqa: E402
from hc_valuation.engine.models import Readiness, Severity  # noqa: E402
from hc_valuation.ingest.reader import read_workbook       # noqa: E402
from hc_valuation.ingest.schema import ACTIVITY_COLUMNS    # noqa: E402
from hc_valuation.pipeline import RunPaths, execute        # noqa: E402
from hc_valuation.workbooks import SYNTHETIC_SHEET, provider_for  # noqa: E402

CHAIN = ROOT / "data" / "quarters" / "synthetic"
LEDGER = CHAIN / "ledger"
REAL_WORKBOOK = ROOT / "data" / "HC_Mock_Portfolio_Data.xlsx"
REVIEWER = "Reviewer A (synthetic test)"
PUBLISHER = "Reviewer B (synthetic test)"
GENERATED_AT = {"2026Q3": datetime(2026, 10, 12, tzinfo=timezone.utc), "2026Q4": datetime(2027, 1, 12, tzinfo=timezone.utc),
                "2027Q1": datetime(2027, 4, 12, tzinfo=timezone.utc), "2027Q2": datetime(2027, 7, 12, tzinfo=timezone.utc)}
LABEL = {"2026Q3": "Q3 2026", "2026Q4": "Q4 2026", "2027Q1": "Q1 2027", "2027Q2": "Q2 2027"}
NEXT = {"2026Q3": "2026Q4", "2026Q4": "2027Q1", "2027Q1": "2027Q2"}
MARKER_TEXT = [
    ["SYNTHETIC TEST DATA"],
    ["This workbook was generated by scripts/synthetic_chain.py to attack the valuation engine."],
    ["Every company, number and event is invented. Nothing here is a real position or a real market observation."],
    ["The Portfolio tab is the previous quarter's booked book as the engine emitted it after scripted reviewer decisions;"],
    ["only the activity rows and a few operating metrics (listed in the Synthetic Edits tab) were written by hand."],
]


# ----------------------------------------------------------------------------- helpers

def quarter_dir(slug: str) -> Path:
    return CHAIN / slug


def workbook_path(slug: str) -> Path:
    return quarter_dir(slug) / f"SYNTHETIC_portfolio_{LABEL[slug].replace(' ', '_')}.xlsx"


def policy_path(slug: str) -> Path:
    return ROOT / "rules" / f"{slug}.yaml"


def ensure_policy(slug: str) -> Path:
    p = policy_path(slug)
    if not p.exists():
        prev = {"2026Q4": "2026Q3", "2027Q1": "2026Q4", "2027Q2": "2027Q1"}[slug]
        write_next_policy(policy_path(prev), note="synthetic test chain: inherits everything, window only")
    return p


def paths_for(slug: str) -> RunPaths:
    wb = REAL_WORKBOOK if slug == "2026Q3" else workbook_path(slug)
    return RunPaths.default(root=ROOT, workbook=wb, policy=ensure_policy(slug), ledger_dir=LEDGER)


def run_quarter(slug: str, *, adjudicate: bool = False):
    paths = paths_for(slug)
    provider = provider_for(ROOT, paths.policy)
    return execute(paths, provider=provider, adjudicate=adjudicate, generated_at=GENERATED_AT[slug]), paths, provider


def _add_marker(wb: openpyxl.Workbook, edits: list[list[Any]] | None = None) -> None:
    if SYNTHETIC_SHEET not in wb.sheetnames:
        ws = wb.create_sheet(SYNTHETIC_SHEET, 0)
        for row in MARKER_TEXT:
            ws.append(row)
        ws.column_dimensions["A"].width = 120
    if edits:
        ws2 = wb.create_sheet("Synthetic Edits")
        ws2.append(["Company", "Column", "Was", "Now", "Why (the case this edit builds)"])
        for row in edits:
            ws2.append(row)
        for col, w in zip("ABCDE", (22, 20, 12, 12, 90)):
            ws2.column_dimensions[col].width = w


def _find(ws, header: str) -> int:
    for j, cell in enumerate(ws[1], start=1):
        if cell.value == header:
            return j
    raise KeyError(header)


def _row_of(ws, company: str) -> int:
    col = _find(ws, "Company")
    for r in range(2, ws.max_row + 1):
        if ws.cell(row=r, column=col).value == company:
            return r
    raise KeyError(company)


def _write_activity(ws, rows: list[dict[str, Any]]) -> None:
    cols = list(ACTIVITY_COLUMNS)
    for r in rows:
        ws.append([r.get(c) for c in cols])


def _book(slug_prev_build: Path) -> dict[str, Any]:
    """The emitted Portfolio tab as a dict of company -> column -> value (the opening book)."""
    wb = openpyxl.load_workbook(slug_prev_build, data_only=False)
    ws = wb["Portfolio"]
    headers = [c.value for c in ws[1]]
    out = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        d = dict(zip(headers, row))
        if d.get("Company"):
            out[d["Company"]] = d
    return out


# ----------------------------------------------------------------------------- decisions

# Named, non-default decisions. Everything else not Ready takes the policy recommendation (below).
# Format: quarter -> company -> (booked expression, rule ids addressed, reason, evidence)
DECISIONS: dict[str, dict[str, dict[str, Any]]] = {
    "2026Q3": {
        "Drayvenn": {"closing_cap": 4100.0, "reason": "SYNTHETIC test decision: quarter-end market cap of $4,100M supplied "
                                                        "as the 30 Sep 2026 close (invented; the ticker is fictional)."},
        "Oakenvale": {"suggestion": ("X-102", "structure_adjusted"), "reason": "SYNTHETIC test decision: take the policy's 25% junior-class "
                                                                       "haircut on the recap until the waterfall is read."},
        "Birchhollow": {"suggestion": ("X-202", "calibrate"), "reason": "SYNTHETIC test decision: book the comps-calibrated "
                                                                        "alternative for a 65-month-old round with shrinking ARR."},
    },
    "2026Q4": {
        "Drayvenn": {"closing_cap": 3700.0, "reason": "SYNTHETIC test decision: 31 Dec 2026 market cap of $3,700M supplied (invented)."},
        "Umberly": {"suggestion": ("X-102", "hold_prior"), "reason": "SYNTHETIC test decision: hold the prior mark on the down round; "
                                                                      "the company has three months of cash and the round may not be the last word."},
    },
    "2027Q1": {
        "Drayvenn": {"closing_cap": 3900.0, "reason": "SYNTHETIC test decision: 31 Mar 2027 market cap of $3,900M supplied (invented)."},
        "Fernwave": {"closing_cap": 2200.0, "reason": "SYNTHETIC test decision: 31 Mar 2027 market cap of $2,200M supplied (invented)."},
    },
    "2027Q2": {
        "Drayvenn": {"closing_cap": 4000.0, "reason": "SYNTHETIC test decision: 30 Jun 2027 market cap of $4,000M supplied (invented)."},
        "Fernwave": {"closing_cap": 2500.0, "reason": "SYNTHETIC test decision: 30 Jun 2027 market cap of $2,500M supplied (invented)."},
        "Thornmill Systems": {"closing_cap": 2400.0, "reason": "SYNTHETIC test decision: 30 Jun 2027 market cap of $2,400M supplied (invented)."},
    },
}


def decide(slug: str) -> list[dict[str, Any]]:
    """Record one decision per not-Ready position into the chain ledger. Returns the records."""
    r, paths, provider = run_quarter(slug)
    run = r.run
    cfg = r.config
    quarter = cfg.quarter.label
    created = (GENERATED_AT[slug].date()).isoformat()
    records: list[dict[str, Any]] = []
    named = DECISIONS.get(slug, {})
    for c in run.companies:
        if c.readiness is Readiness.READY:
            continue
        addressed = set(c.override.rule_ids_addressed) if c.override else set()
        open_ids = sorted({f.rule_id for f in c.flags if f.severity in (Severity.BLOCK, Severity.REVIEW)} - addressed)
        spec = named.get(c.company)
        rec: dict[str, Any] = {"company": c.company, "quarter": quarter, "proposed": float(c.proposed_mark),
                               "approver": REVIEWER, "created_at": created}
        if spec and "closing_cap" in spec:
            cap = float(spec["closing_cap"])
            rule = next((f.rule_id for f in c.flags if f.rule_id in ("X-113", "X-101")), open_ids[0] if open_ids else "X-113")
            rec.update(booked=round(c.ownership_after * cap, 6), reason=spec["reason"],
                       rule_ids_addressed=sorted(set(open_ids) | {rule}), source_suggestion=f"{rule}/price",
                       evidence={"kind": "closing_price", "as_of": cfg.quarter.measurement_date.isoformat(),
                                 "market_cap_musd": cap, "source": "SYNTHETIC test decision (invented)",
                                 "ownership": c.ownership_after})
        elif spec and "suggestion" in spec:
            rid, key = spec["suggestion"]
            flag = next(f for f in c.flags if f.rule_id == rid)
            sug = next((s for s in flag.suggestions if s.key == key), None)
            if sug is None:   # the alternative was not produced this quarter (e.g. no live history): fall back, and say so
                rec.update(booked=float(c.proposed_mark), reason=spec["reason"] + " [alternative not available; booked as proposed]",
                           rule_ids_addressed=open_ids, source_suggestion=f"{rid}/as_proposed")
            else:
                rec.update(booked=float(sug.booked), reason=spec["reason"], rule_ids_addressed=open_ids,
                           source_suggestion=f"{rid}/{key}")
        else:
            pr = c.recommendation
            if pr is not None:
                rec.update(booked=float(pr.booked), reason=f"Policy recommendation ({pr.rule_id}/{pr.key}): {pr.label}",
                           rule_ids_addressed=open_ids, source_suggestion=f"{pr.rule_id}/{pr.key}")
            else:
                rec.update(booked=float(c.proposed_mark), reason="Accepted as proposed (no actionable recommendation).",
                           rule_ids_addressed=open_ids)
        append_override(paths.overrides, rec)
        records.append(rec)
    # the log a reader can audit without opening the yaml
    lines = [f"# Simulated reviewer decisions — {quarter} (synthetic chain)", "",
             f"Run `{run.manifest.run_id}` on `{paths.workbook.name}`, provider `{provider}`. One decision per position that was "
             "not Ready; every one recorded under the reviewer's name in `ledger/overrides.yaml`.", "",
             "| Company | Readiness | Proposed | Booked | Rules addressed | Reason |", "|---|---|---:|---:|---|---|"]
    by = run.by_company()
    for rec in records:
        c = by[rec["company"]]
        lines.append(f"| {rec['company']} | {c.readiness.value} | {rec['proposed']:.3f} | {rec['booked']:.3f} | "
                     f"{', '.join(rec['rule_ids_addressed'])} | {rec['reason']} |")
    (LEDGER / f"decisions_{slug}.md").write_text("\n".join(lines) + "\n")
    return records


def publish_and_build(slug: str) -> Path:
    """Publish the decided book under the second name and emit next quarter's input with `build`."""
    r, paths, provider = run_quarter(slug)
    waiting = [c.company for c in r.run.companies if c.readiness is not Readiness.READY]
    if waiting:
        raise SystemExit(f"{slug}: {len(waiting)} position(s) still not Ready after decisions: {waiting}")
    rec = publish_run(r.run, ROOT, approver=PUBLISHER, note=f"SYNTHETIC test chain — {LABEL[slug]}",
                      published_at=GENERATED_AT[slug], published=paths.published_dir)
    out = CHAIN / "build" / slug
    if out.exists():
        shutil.rmtree(out)
    cmd = [sys.executable, "-m", "hc_valuation", "build", "--input", str(paths.workbook), "--policy", str(paths.policy),
           "--ledger-dir", str(LEDGER), "--out", str(out)] + (["--provider", provider] if provider else [])
    res = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    if res.returncode != 0:
        raise SystemExit(f"build failed for {slug}:\n{res.stdout}\n{res.stderr}")
    print(f"published {rec['quarter']} as {rec['status']} (run {rec['run_id']}, booked {rec['booked_nav']:,.1f}); built into {out}")
    return out


# ----------------------------------------------------------------------------- the quarters' activity

def _ev(d: str, company: str, event: str, detail: str, value=None, inv=None, own=None, proceeds=None, notes: str = "") -> dict[str, Any]:
    return {"Date": datetime.fromisoformat(d), "Company": company, "Event": event, "Detail": detail,
            "Post-Money / Deal Value ($M)": value, "HC Investment ($M)": inv, "HC Ownership After (FD %)": own,
            "Proceeds to HC ($M)": proceeds, "Notes": notes}


def q4_events(book: dict[str, Any]) -> list[dict[str, Any]]:
    own = lambda c: float(book[c]["Ownership (FD %)"])                  # noqa: E731
    post = lambda c: float(book[c]["Latest Post-Money ($M)"])           # noqa: E731
    return [
        _ev("2026-10-05", "Gryphonel", "Acquisition (Closed)", "All-cash acquisition", 133.0, None, None, round(own("Gryphonel") * 133.0, 4),
            "Regulatory approval received; transaction closed and cash received in full."),
        _ev("2026-10-09", "Cindral", "Distribution", "Escrow release", None, None, None, 1.5, "Escrow released 60 days after the August close."),
        _ev("2026-10-12", "Nimbrel", "Convertible Note", "$3.0M bridge note, $60.0M valuation cap", None, 0.4, None, None,
            "Uncapped interest, converts at next priced round. HC participated in the note."),
        _ev("2026-10-14", "Emberfold", "Priced Equity Round", "Series A", 40.0, None, 0.065, None,
            "$9.0M round led by a new investor. The bridge note rolled into the round at its $32.0M cap. HC did not participate."),
        _ev("2026-10-20", "Duskfern", "Priced Equity Round", "Series B", 150.0, 1.0, 0.089, None,
            "$25.0M round led by a new investor. HC participated; the bridge note rolled into the round."),
        _ev("2026-11-02", "Halcyra", "Priced Equity Round", "Series B", 50.0, None, 0.071, None,
            "$12.0M round led by a new investor at the term-sheet price. HC did not participate."),
        _ev("2026-11-05", "Fernwave", "Secondary Sale", "HC sold 25% of its position", round(post("Fernwave") * 1.05, 4), None, 0.030,
            round(0.010 * post("Fernwave") * 1.05, 4), "Buyer paid 5.0% above the Series D price."),
        _ev("2026-11-06", "Ironquill Security", "Secondary Sale", "HC sold 20% of its position", round(post("Ironquill Security") * 1.051, 4), None, 0.030,
            round(0.008 * post("Ironquill Security") * 1.051, 4), "Buyer paid 5.1% above the Series D price."),
        _ev("2026-11-10", "Umberly", "Priced Equity Round", "Series C (down round)", 180.0, None, 0.075, None,
            "$30.0M round led by a new investor at a lower price than the Series B. HC did not participate."),
        _ev("2026-11-12", "Quillbrook Labs", "New Investment", "Seed — Fund III, Cybersecurity", 18.0, 1.5, 0.083, None,
            "First cheque from Fund III into a Cybersecurity seed round."),
        _ev("2026-11-18", "Beltrix", "Shutdown", "Ceased operations", None, None, None, 0.2,
            "Board voted to wind down. Residual cash distributed to investors."),
        _ev("2026-11-20", "Underbough", "Shutdown", "Ceased operations", None, None, None, None,
            "Board voted to wind down. No recovery expected."),
        _ev("2026-11-24", "Jettamar", "Acquisition (Announced)", "Definitive agreement signed, all cash", 90.0, None, None, None,
            "Expected to close in Q1 2027, subject to regulatory approval. No cash received."),
        _ev("2026-12-01", "Dovelane Systems", "Term Sheet Signed", "Series C term sheet at ~$83.04M post", round(post("Dovelane Systems") * 0.80, 4), None, None, None,
            "Not closed; diligence underway, expected to close Q1."),
        _ev("2026-12-02", "Aravine", "Term Sheet Signed", "Series C term sheet at ~$103.0M post", 103.0, None, None, None,
            "Not closed; expected to close Q1."),
        _ev("2026-12-04", "Marrowick Bio", "Ownership Adjustment", "Warrant exercise", None, 0.1, 0.019, None,
            "HC exercised the warrants attached to the Series B."),
        _ev("2026-12-08", "Wildebrook", "Priced Equity Round", "Series B", 120.0, None, round(own("Wildebrook") * 0.80, 4), None,
            "$25.0M round led by a new investor. HC did not participate."),
        _ev("2026-12-10", "Solvantra", "Priced Equity Round", "Series B", 150.0, 1.65, round(own("Solvantra") + 0.010, 4), None,
            "$30.0M round led by a new investor. HC participated."),
        _ev("2026-12-12", "Kilnbrook", "Priced Equity Round", "Series B", 120.0, 1.2, round(own("Kilnbrook") + 0.009, 4), None,
            "$24.0M round led by a new investor. HC participated."),
        _ev("2026-12-15", "Nimbrel", "Priced Equity Round", "Series B", 70.0, 0.6, 0.077, None,
            "$15.0M round led by a new investor. HC participated; the bridge note rolled into the round at its cap."),
        _ev("2026-12-18", "Yarrowbank", "Convertible Note", "$1.0M bridge note, $45.0M valuation cap", None, 0.3, None, None,
            "Uncapped interest, converts at next priced round. HC participated in the note."),
        _ev("2026-12-20", "Pinwhistle", "Acquisition (Announced)", "Definitive agreement signed, all cash", 60.0, None, None, None,
            "Expected to close in Q1 2027. No cash received."),
    ]


# Portfolio-tab metric edits for Q4: (company, column, new value, why)
Q4_EDITS = [
    ("Vellichor Systems", "ARR Growth (YoY %)", -0.15, "ARR growth exactly at the -15% REVIEW threshold (boundary: strict '<' means MONITOR only)"),
    ("Zealwick", "Cash ($M)", 3.5, "with burn 0.5 → runway 7.0, aged 6.0: exactly at the 6-month REVIEW threshold (boundary)"),
    ("Zealwick", "Net Burn ($M/mo)", 0.5, "see above"),
    ("Northquill", "Cash ($M)", 6.99, "with burn 1.0 → runway 6.99, aged 5.99: just inside REVIEW"),
    ("Northquill", "Net Burn ($M/mo)", 1.0, "see above"),
    ("Isoquill", "ARR Growth (YoY %)", -0.20, "no activity, round crosses 48 months in the quarter AND ARR shrinking: two REVIEW families"),
    ("Umberly", "Cash ($M)", 4.1, "unchanged runway (3.1 months) so the down round is named on the runway flag"),
]


def q1_events(book: dict[str, Any]) -> list[dict[str, Any]]:
    own = lambda c: float(book[c]["Ownership (FD %)"])                  # noqa: E731
    post = lambda c: float(book[c]["Latest Post-Money ($M)"])           # noqa: E731
    return [
        _ev("2027-01-08", "Fernwave", "IPO", "Listed on NYSE", 2400.0, None, 0.030, None,
            "Priced at the top of the range. HC shares subject to a 180-day lock-up."),
        _ev("2027-01-12", "Umberly", "Bankruptcy (Chapter 11)", "Filed for Chapter 11 reorganisation", None, None, None, None,
            "Debtor-in-possession financing from existing lenders; plan of reorganisation expected in Q2."),
        _ev("2027-01-15", "Pinwhistle", "Acquisition (Terminated)", "Buyer walked away", None, None, None, None,
            "Regulatory approval denied; the agreement was terminated."),
        _ev("2027-01-20", "Halcyra", "Acquisition (Closed)", "Acquired for stock of the buyer", 65.0, None, None, None,
            "All-stock consideration; the buyer is privately held."),
        _ev("2027-01-26", "Yarrowbank", "Note Repaid", "Bridge note repaid with interest", None, None, None, 0.31,
            "Company repaid the note from operating cash."),
        _ev("2027-02-03", "Mirthstone", "Secondary Purchase", "HC bought from a departing angel", post("Mirthstone"), round(0.002 * post("Mirthstone"), 4),
            round(own("Mirthstone") + 0.002, 4), None, "Bought at the Series B price."),
        _ev("2027-02-10", "Foxtrellis", "Priced Equity Round", "Series B extension (same terms)", post("Foxtrellis"), 0.5, round(own("Foxtrellis") + 0.001, 4), None,
            "Extension of the prior round at the same post-money."),
        _ev("2027-02-14", "Tarnwick Aerospace", "Priced Equity Round", "Series A-1 (recap)", 9.0, 0.2, 0.095, None,
            "$2.0M insider-led round. HC participated."),
        _ev("2027-02-18", "Arcfoundry", "Acquisition (Closed)", "All-cash acquisition", 200.0, None, None, round(own("Arcfoundry") * 200.0 * 0.90, 4),
            "Transaction closed; 10% of the consideration is held back for 12 months."),
        _ev("2027-02-20", "Knollward", "Acquisition (Closed)", "All-cash acquisition", 30.0, None, None, None, "Transaction closed."),
        _ev("2027-03-02", "Aravine", "Priced Equity Round", "Series C", 110.0, 1.0, 0.104, None, "$20.0M round led by HC."),
        _ev("2027-03-05", "Lumetra", "Priced Equity Round", "Series A", 13.0, None, 0.085, None, "$3.0M insider-led round. No new investor."),
        _ev("2027-03-09", "Zephrine", "Priced Equity Round", "Series A", 30.0, None, 0.130, None,
            "$8.0M round led by a new investor. HC did not participate."),
        _ev("2027-03-12", "Quillbrook Labs", "Priced Equity Round", "Series A", 40.0, 1.0, 0.108, None,
            "$8.0M round led by a new investor. HC participated pro rata."),
        _ev("2027-03-15", "Redgrove Health", "Term Sheet Signed", "Series B term sheet at ~$40.0M post", 40.0, None, None, None, "Signed the morning of the close."),
        _ev("2027-03-15", "Redgrove Health", "Priced Equity Round", "Series B", 40.0, 0.5, round(own("Redgrove Health") + 0.0125, 4), None,
            "$10.0M round led by a new investor. HC participated."),
        _ev("2027-03-25", "Wrenfield Data", "Shutdown", "Ceased operations; assets sold", None, None, None, 14.0,
            "Board voted to wind down; asset sale returned more than the carrying value."),
    ]


Q1_EDITS = [
    ("Birchhollow", "ARR Growth (YoY %)", -0.25, "deteriorating further on a 70-month-old round"),
    ("Jupelan", "Cash ($M)", 2.0, "with burn 1.0 → runway 2.0, aged 1.0"),
    ("Jupelan", "Net Burn ($M/mo)", 1.0, "see above"),
]


def q2_events(book: dict[str, Any]) -> list[dict[str, Any]]:
    own = lambda c: float(book[c]["Ownership (FD %)"])                  # noqa: E731
    post = lambda c: float(book[c]["Latest Post-Money ($M)"])           # noqa: E731
    return [
        _ev("2027-04-06", "Arcfoundry", "Distribution", "Holdback released", None, None, None, round(float(book["Arcfoundry"]["Ownership (FD %)"] or 0.064) * 200.0 * 0.10, 4),
            "Holdback released on schedule."),
        _ev("2027-04-10", "Umberly", "Priced Equity Round", "Series C-1 (recap)", 40.0, None, 0.030, None,
            "Plan of reorganisation confirmed; new money from existing lenders. HC did not participate."),
        _ev("2027-04-15", "Pellagrin", "Priced Equity Round", "Series B extension (same terms)", post("Pellagrin"), 0.5, round(own("Pellagrin") + 0.003, 4), None,
            "Extension of the prior round at the same post-money."),
        _ev("2027-05-05", "Nimbrel", "Secondary Sale", "HC sold 40% of its position", post("Nimbrel"), None, round(own("Nimbrel") * 0.6, 4),
            round(own("Nimbrel") * 0.4 * post("Nimbrel"), 4), "Buyer paid the Series B price."),
        _ev("2027-05-12", "Elmsworth Data", "Acquisition (Announced)", "Definitive agreement signed, all cash", 900.0, None, None, None,
            "Expected to close in Q3 2027. No cash received."),
        _ev("2027-05-18", "Gorseline", "Priced Equity Round", "Series B", 90.0, None, 0.090, None,
            "$20.0M round led by a new investor. HC did not participate."),
        _ev("2027-05-25", "Kestwick", "Shutdown", "Ceased operations", None, None, None, None, "Board voted to wind down. No recovery expected."),
        _ev("2027-06-01", "Tidewell Health", "Convertible Note", "$2.0M bridge note, $20.0M valuation cap", None, None, None, None,
            "Uncapped interest, converts at next priced round. HC did not participate."),
        _ev("2027-06-08", "Mardellan", "Secondary Sale", "HC sold 50% of its position", 5000.0, None, round(own("Mardellan") * 0.5, 4),
            round(own("Mardellan") * 0.5 * 5000.0, 4), "Buyer paid 12% below the Series D+ price."),
        _ev("2027-06-15", "Thornmill Systems", "Direct Listing", "Listed on Nasdaq", 2500.0, None, own("Thornmill Systems"), None,
            "Direct listing; no lock-up."),
        _ev("2027-06-20", "Elmsworth Data", "Acquisition (Closed)", "All-cash acquisition", 900.0, None, None, round(own("Elmsworth Data") * 900.0, 4),
            "Closed ahead of schedule; cash received in full."),
        _ev("2027-06-22", "Oakenvale", "Acquisition (Closed)", "All-cash acquisition", 30.0, None, None, round(own("Oakenvale") * 30.0, 4),
            "Transaction closed and cash received."),
        _ev("2027-06-25", "Dovelane Systems", "Priced Equity Round", "Series C (down round)", round(post("Dovelane Systems") * 0.80, 4), None, 0.050, None,
            "$15.0M round led by a new investor at the term-sheet price. HC did not participate."),
    ]


Q2_EDITS = [
    ("Northquill", "Cash ($M)", 1.0, "with burn 1.0 → runway 1.0, aged 0.0"),
    ("Stonegather", "Cash ($M)", 0.0, "no cash: runway 0"),
]

EVENTS = {"2026Q4": (q4_events, Q4_EDITS), "2027Q1": (q1_events, Q1_EDITS), "2027Q2": (q2_events, Q2_EDITS)}


def write_workbook(slug: str) -> Path:
    prev = {"2026Q4": "2026Q3", "2027Q1": "2026Q4", "2027Q2": "2027Q1"}[slug]
    src_dir = CHAIN / "build" / prev
    src = src_dir / f"portfolio_{LABEL[slug].replace(' ', '_')}.xlsx"
    if not src.exists():
        raise SystemExit(f"{src} missing: run the previous quarter's `decide` first")
    out = workbook_path(slug)
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(src_dir / "open_items_carry.yaml", out.parent / "open_items_carry.yaml")
    book = _book(src)
    wb = openpyxl.load_workbook(src)
    ws = wb["Portfolio"]
    fn, edits = EVENTS[slug]
    edit_rows = []
    for company, column, value, why in edits:
        r = _row_of(ws, company)
        c = _find(ws, column)
        was = ws.cell(row=r, column=c).value
        ws.cell(row=r, column=c).value = value
        edit_rows.append([company, column, was, value, why])
    act = wb[f"{LABEL[slug]} Activity"]
    _write_activity(act, fn(book))
    _add_marker(wb, edit_rows)
    wb.save(out)
    ensure_policy(slug)
    write_malformed(slug, out)
    print(f"wrote {out} ({len(fn(book))} events, {len(edits)} metric edits)")
    return out


# ----------------------------------------------------------------------------- malformed variants

def write_malformed(slug: str, clean: Path) -> None:
    """Deliberately broken copies of the clean workbook, each with one defect, under malformed/<slug>/.
    Never part of the chain; each must be refused or blocked by ingest."""
    mdir = CHAIN / "malformed" / slug
    if mdir.exists():
        shutil.rmtree(mdir)
    mdir.mkdir(parents=True)
    label = LABEL[slug]
    act_name = f"{label} Activity"
    year = label.split()[1]

    def variant(name: str, mutate) -> None:
        wb = openpyxl.load_workbook(clean)
        mutate(wb)
        wb.save(mdir / f"SYNTHETIC_MALFORMED_{name}_{label.replace(' ', '_')}.xlsx")

    def first_priced_round_row(ws) -> int:
        ev = _find(ws, "Event")
        for r in range(2, ws.max_row + 1):
            if ws.cell(row=r, column=ev).value == "Priced Equity Round":
                return r
        raise KeyError("no priced round")

    variant("missing_post_money", lambda wb: wb[act_name].cell(row=first_priced_round_row(wb[act_name]),
                                                               column=_find(wb[act_name], "Post-Money / Deal Value ($M)")).__setattr__("value", None))
    variant("unreadable_cell", lambda wb: wb[act_name].cell(row=first_priced_round_row(wb[act_name]),
                                                            column=_find(wb[act_name], "HC Ownership After (FD %)")).__setattr__("value", "TBD"))

    def duplicate_row(wb):
        ws = wb["Portfolio"]
        ws.append([c.value for c in ws[2]])
    variant("duplicate_portfolio_row", duplicate_row)

    def unknown_event(wb):
        ws = wb[act_name]
        ws.append([datetime(int(year), {"Q1": 2, "Q2": 5, "Q3": 8, "Q4": 11}[label.split()[0]], 3), ws.cell(row=2, column=2).value,
                   "SPAC Merger", "Merged into a listed SPAC", 500.0, None, 0.02, None, "Structure not in the schema."])
    variant("unknown_event_type", unknown_event)

    def out_of_window(wb):
        ws = wb[act_name]
        r = first_priced_round_row(ws)
        ws.cell(row=r, column=_find(ws, "Date")).value = datetime(int(year) + 1, 1, 15)
    variant("event_after_measurement_date", out_of_window)

    def conflicting_rows(wb):
        ws = wb[act_name]
        ev = _find(ws, "Event")
        for r in range(2, ws.max_row + 1):
            if ws.cell(row=r, column=ev).value in ("Shutdown", "Acquisition (Closed)"):
                company = ws.cell(row=r, column=_find(ws, "Company")).value
                d = ws.cell(row=r, column=_find(ws, "Date")).value
                ws.append([d.replace(day=min(28, d.day + 7)), company, "Priced Equity Round", "Series Z", 99.0, None, 0.05, None,
                           "A financing dated after the exit — cannot both be true."])
                return
        raise KeyError("no terminal event to contradict")
    variant("financing_after_exit", conflicting_rows)

    def prior_mark_off(wb):
        ws = wb["Portfolio"]
        c = _find(ws, "Prior Mark ($M)")
        ws.cell(row=3, column=c).value = float(ws.cell(row=3, column=c).value or 0) + 1.0
    variant("prior_mark_unreconciled", prior_mark_off)

    def euro_cell(wb):
        ws = wb[act_name]
        r = first_priced_round_row(ws)
        ws.cell(row=r, column=_find(ws, "Post-Money / Deal Value ($M)")).value = "€120.0M"
    variant("non_usd_currency", euro_cell)

    def wrong_quarter_sheet(wb):
        wb[act_name].title = f"Q{int(label.split()[0][1]) % 4 + 1} {year} Activity"
    variant("activity_sheet_wrong_quarter", wrong_quarter_sheet)

    def duplicate_activity(wb):
        ws = wb[act_name]
        ws.append([c.value for c in ws[2]])
    variant("duplicate_activity_row", duplicate_activity)


# ----------------------------------------------------------------------------- compare

def compare(slug: str) -> int:
    """Run the quarter and diff against expectations/<slug>.yaml. Exit code = number of mismatches."""
    exp_path = CHAIN / "expectations" / f"{slug}.yaml"
    exp = yaml.safe_load(exp_path.read_text())
    r, paths, provider = run_quarter(slug)
    run = r.run
    by = run.by_company()
    mismatches: list[str] = []
    superseded = 0
    for company, e in (exp.get("companies") or {}).items():
        c = by.get(company)
        if c is None:
            mismatches.append(f"{company}: not in run")
            continue
        if e.get("superseded"):
            # An expectation shown to be a derivation error, kept verbatim with its `resolution:` so
            # the record of what was expected first survives; it is reported, not compared.
            superseded += 1
            print(f"  superseded {company}: {e.get('resolution', '').strip()[:160]}")
            continue
        if "proposed_mark" in e and abs(float(e["proposed_mark"]) - c.proposed_mark) > float(e.get("tolerance", 0.01)):
            mismatches.append(f"{company}: proposed {c.proposed_mark:.4f} != expected {float(e['proposed_mark']):.4f}")
        if "readiness" in e and c.readiness.value != e["readiness"]:
            mismatches.append(f"{company}: readiness {c.readiness.value} != expected {e['readiness']}")
        if "disposition" in e and c.disposition.value != e["disposition"]:
            mismatches.append(f"{company}: disposition {c.disposition.value} != expected {e['disposition']}")
        if "realized_quarter" in e and abs(float(e["realized_quarter"]) - c.realized_quarter) > 0.01:
            mismatches.append(f"{company}: realized {c.realized_quarter:.4f} != expected {float(e['realized_quarter']):.4f}")
        got = {f.rule_id for f in c.flags}
        for rid in e.get("flags_include", []) or []:
            if rid not in got:
                mismatches.append(f"{company}: expected flag {rid} missing (has {sorted(got)})")
        for rid in e.get("flags_exclude", []) or []:
            if rid in got:
                mismatches.append(f"{company}: flag {rid} fired but was not expected (has {sorted(got)})")
        if "status_after" in e and c.status_after.value != e["status_after"]:
            mismatches.append(f"{company}: status {c.status_after.value} != expected {e['status_after']}")
    t = exp.get("totals") or {}
    if "readiness" in t and dict(run.totals.readiness) != t["readiness"]:
        mismatches.append(f"totals.readiness {dict(run.totals.readiness)} != expected {t['readiness']}")
    if "positions" in t and run.totals.positions != t["positions"]:
        mismatches.append(f"totals.positions {run.totals.positions} != expected {t['positions']}")
    blocking = [v for v in run.validation if v.blocking]
    if exp.get("blocking_validation", 0) != len(blocking):
        mismatches.append(f"blocking validation issues {len(blocking)} != expected {exp.get('blocking_validation', 0)}: "
                          + "; ".join(f"{v.rule_id} {v.company}" for v in blocking[:8]))
    print(f"{slug}: run {run.manifest.run_id} provider {provider} readiness {dict(run.totals.readiness)} "
          f"prior {run.totals.prior_nav:,.1f} proposed {run.totals.proposed_nav:,.1f} booked {run.totals.booked_nav:,.1f}")
    for m in mismatches:
        print("  MISMATCH", m)
    print(f"{len(mismatches)} mismatch(es) against {exp_path.relative_to(ROOT)}"
          + (f"; {superseded} expectation(s) superseded by a documented derivation error" if superseded else ""))
    return len(mismatches)


# ----------------------------------------------------------------------------- main

def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    stage = argv[0]
    slug = argv[1] if len(argv) > 1 else "2026Q3"
    LEDGER.mkdir(parents=True, exist_ok=True)
    if stage == "q3":
        decide("2026Q3")
        publish_and_build("2026Q3")
    elif stage == "workbook":
        write_workbook(slug)
    elif stage == "run":
        return compare(slug)
    elif stage == "decide":
        decide(slug)
        publish_and_build(slug)
    elif stage == "reset":
        for p in (LEDGER, CHAIN / "build"):
            if p.exists():
                shutil.rmtree(p)
        print("chain ledger and builds removed; workbooks and expectations kept")
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
